In [4]:
import numpy as np

This imports the numpy library

In [5]:
integer = np.array([[1,2,3] , [4,5,6]])
integer

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [11]:
for row in integer:
    for col in row:
        
        print(col, end=' ')
        
    print()

1 2 3 
4 5 6 


In [28]:
for i in integer.flat:
    print(i, end=' ')

{1, 2, 3} {4, 5, 6} 

In [20]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
np.full((3, 5), 15)

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [23]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [24]:
np.arange(10, 1, -2)


array([10,  8,  6,  4,  2])

In [26]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [30]:
np.arange(1,21).reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [34]:
np.arange(1,100_001).reshape(4, 25000)


array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

ARRAY OPERATOR

In [5]:
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [6]:
numbers*2

array([ 2,  4,  6,  8, 10])

In [7]:
numbers**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [8]:
numbers
numbers +=10
numbers

array([11, 12, 13, 14, 15])

In [9]:
numbers2 = np.linspace(1.1, 5.5, 5)
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [43]:
numbers * numbers2

array([ 45.1,  92.4, 141.9, 193.6, 247.5])

In [47]:
numbers >= 13
numbers

array([41, 42, 43, 44, 45])

In [45]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [46]:
numbers == numbers2

array([False, False, False, False, False])

This is array of 4 students and 3 subjects

In [50]:
grades = np.array([[87,96,70],
                  [100, 87, 90],
                  [94, 77, 90],
                  [100, 81, 82] ])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [51]:
grades.min()

70

In [52]:
grades.sum()

1054

In [53]:
grades.mean()

87.83333333333333

In [55]:
grades.var()

77.30555555555556

axis=0 is a column by column application

In [56]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

axis = 1 is a row by row application

In [57]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [58]:
numbers = np.array([1,4,9,16,25,36])
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [59]:
numbers2 = np.arange(1,7)*10
numbers2

array([10, 20, 30, 40, 50, 60])

In [60]:
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

In [61]:
np.multiply(numbers2, 5)

array([ 50, 100, 150, 200, 250, 300])

In [62]:
numbers3 = numbers2.reshape(2,3)
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [63]:
numbers4 = np.array([2,4,6])
np.multiply(numbers3,numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

The columns size has to match but the rows size don't have to match in the above code

Indexing and Slicing

In [64]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [65]:
grades[0,1]

96

0 = rows 1 = column

In [66]:
grades[1]

array([100,  87,  90])

only one value, means the row, its a array

In [67]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

, non consecutive rows and columns, : is consicutive rows and colummns

In [71]:
grades[[1,3]]

array([[100,  87,  90],
       [100,  81,  82]])

 brackets with comma gives the non consecutive rows

In [72]:
grades[:,0]

array([ 87, 100,  94, 100])

In [74]:
grades[:,1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [75]:
grades[:, [0,2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

SHALLOW COPIES

In [6]:
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [78]:
numbers2 = numbers.view()
numbers2

array([1, 2, 3, 4, 5])

In [79]:
id(numbers)

1773000543856

In [80]:
id(numbers2)

1773000470768

In [81]:
numbers[1] *= 10
numbers2
numbers

array([ 1, 20,  3,  4,  5])

In [82]:
numbers2[1] /= 10
numbers

array([1, 2, 3, 4, 5])

In [83]:
numbers2 = numbers[0:3]
numbers2

array([1, 2, 3])

In [84]:
id(numbers)

1773000543856

In [85]:
numbers[1] *= 20
numbers

array([ 1, 40,  3,  4,  5])

In [86]:
numbers2

array([ 1, 40,  3])