In [1]:
import numpy as np


In [2]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.full((2,3), 10)

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
np.arange(1,10,5)

array([1, 6])

In [16]:
np.linspace(5,2, num=5)

array([5.  , 4.25, 3.5 , 2.75, 2.  ])

In [24]:
np.arange(1,100001).reshape(4, 25000)


array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [25]:
numbers=np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [26]:
numbers**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [27]:
numbers
numbers += 10
numbers

array([11, 12, 13, 14, 15])

In [31]:
numbers2=np.linspace(1.1, 5.5, 5)
numbers2


array([1.1, 2.2, 3.3, 4.4, 5.5])

In [32]:
numbers*numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [36]:
numbers>=13


array([False, False,  True,  True,  True])

In [38]:
numbers == numbers2

array([False, False, False, False, False])

In [40]:
numbers< numbers2

array([False, False, False, False, False])